# nixpacks.toml
[phases.install]
cmds = [
    "cd server && go mod tidy",
    "cd client && npm install",
    "cd tools/markdown-renderer/ && npm install",
]

[phases.setup]
nixPkgs = [
    'nodejs_20',
    'npm',
    'go',
]


[phases.build]
cmds = [
    "./build.sh"
]

[start]
cmd = "./server/app"
